-- Generated service insert SQL from public/serviceCategory.js
INSERT INTO public.services (category, name, title, tier, price, duration, badge, image, description, details_summary, included, excluded, active, rating, reviews) VALUES
  ('Washroom Cleaning', 'Bathroom Cleaning', 'Bathroom Cleaning', 'Deep Washroom Cleaning', NULL, '60 mins', 'BESTSELLER', 'Images/washroom.jpg', 'Machine-assisted deep cleaning to remove stains, grime, and bacteria for complete sanitation.', 'Machine-assisted deep bathroom cleaning.', '["Deep cleaning of toilet seat, washbasin, taps and tiles","Stain removal from key bathroom surfaces","Mirror and fixture cleaning","Floor scrubbing and mopping","Germ control for improved sanitation"]'::jsonb, '["Ceiling and exhaust fan dismantling","Major repair or plumbing work","Acid damage and permanent stain reversal","Cleaning in inaccessible shaft areas"]'::jsonb, true, 4.8, '1.2K'),
  ('Washroom Cleaning', 'Bathroom Cleaning', 'Bathroom Cleaning', 'Basic Washroom Cleaning', NULL, '60 mins', NULL, 'Images/washroom.jpg', 'Surface cleaning, mopping, mirror cleaning, fixture polishing', 'Surface-level bathroom cleaning.', '["Surface cleaning of toilet, washbasin and taps","Mirror cleaning and fixture polishing","Floor mopping","Basic tile wipe-down"]'::jsonb, '["Machine-assisted stain removal","Hard water deposit treatment","Deep grout scrubbing","Ceiling and wall washing"]'::jsonb, true, 4.8, '1.2K'),
  ('Kitchen Cleaning', 'Kitchen Cleaning', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', NULL, '60 mins', 'BESTSELLER', 'Images/Kitchen.jpg', 'Complete cleaning of kitchen surfaces to remove oil, grease, and dirt, ensuring a clean and hygienic cooking space.', 'Deep kitchen cleaning for daily cooking zones.', '["Degreasing of visible kitchen surfaces","Cleaning of countertop, sink and backsplash","Exterior wiping of cabinets and drawers","Hob and chimney exterior cleaning","Floor cleaning and mopping"]'::jsonb, '["Internal cleaning of appliances","Dismantling of chimney filters","Pest-control treatment","Carpentry or plumbing work"]'::jsonb, true, 4.8, '1.2K'),
  ('Kitchen Cleaning', 'Kitchen Cleaning', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', NULL, '60 mins', NULL, 'Images/Kitchen.jpg', 'Intensive removal of oil, grease, and food residue from all key modular kitchen surfaces for a hygienic cooking space.', 'Detailed modular kitchen cleaning.', '["Deep cleaning of shutters, drawers and shelves","Degreasing of cabinet exteriors and accessible interiors","Countertop, sink and backsplash cleaning","Hob and chimney exterior cleaning","Floor scrubbing and mopping"]'::jsonb, '["Full appliance servicing","Removal of permanently damaged laminate marks","Pest-control treatment","Cleaning inside sealed or inaccessible sections"]'::jsonb, true, 4.8, '1.2K'),
  ('Flat Cleaning', 'Home Cleaning', 'Home Cleaning', '1 BHK Flat Cleaning', NULL, '60 mins', 'BESTSELLER', 'Images/flat.jpg', 'Thorough deep cleaning for unfurnished 1 BHK flats, covering all essential living areas.', 'Unfurnished flat deep cleaning.', '["Deep cleaning of living room, bedroom, kitchen, bathroom and balcony","Floor sweeping, mopping and machine scrubbing where required","Dusting of ceilings, fans, switchboards and light fixtures","Kitchen slab, tiles and sink cleaning","Bathroom deep cleaning including toilet seat, washbasin, taps and tiles","Side walls, partition glass and stain removal"]'::jsonb, '["Furnished interiors and furniture cleaning","Glue, paint stain or sticker removal","Terrace cleaning or inaccessible areas","Wet wiping of walls and ceilings","Window tracks and mirror cleaning","Acid damage, permanent stains, or etched surfaces"]'::jsonb, true, 4.8, '1.2K'),
  ('Flat Cleaning', 'Home Cleaning', 'Home Cleaning', '2 BHK Flat Cleaning', NULL, '60 mins', NULL, 'Images/flat.jpg', 'Comprehensive deep cleaning for unfurnished 2 BHK flats, ensuring complete hygiene and freshness.', 'Unfurnished flat deep cleaning.', '["Deep cleaning of all rooms, kitchen, bathrooms and balcony","Floor sweeping, mopping and machine scrubbing where required","Dusting of ceilings, fans, switchboards and light fixtures","Kitchen slab, tiles and sink cleaning","Bathroom deep cleaning including toilet seat, washbasin, taps and tiles","Side walls, partition glass and stain removal"]'::jsonb, '["Furnished interiors and furniture cleaning","Glue, paint stain or sticker removal","Terrace cleaning or inaccessible areas","Wet wiping of walls and ceilings","Window tracks and mirror cleaning","Acid damage, permanent stains, or etched surfaces"]'::jsonb, true, 4.8, '1.2K'),
  ('Flat Cleaning', 'Home Cleaning', 'Home Cleaning', '3 BHK Flat Cleaning', NULL, '60 mins', NULL, 'Images/flat.jpg', 'End-to-end deep cleaning for unfurnished 3 BHK flats with detailed attention to every room.', 'Unfurnished flat deep cleaning.', '["Deep cleaning of all rooms, kitchen, bathrooms and balcony","Floor sweeping, mopping and machine scrubbing where required","Dusting of ceilings, fans, switchboards and light fixtures","Kitchen slab, tiles and sink cleaning","Bathroom deep cleaning including toilet seat, washbasin, taps and tiles","Side walls, partition glass and stain removal"]'::jsonb, '["Furnished interiors and furniture cleaning","Glue, paint stain or sticker removal","Terrace cleaning or inaccessible areas","Wet wiping of walls and ceilings","Window tracks and mirror cleaning","Acid damage, permanent stains, or etched surfaces"]'::jsonb, true, 4.8, '1.2K'),
  ('Car Cleaning', 'Car Cleaning', 'Car Cleaning', 'Cleaning + Exterior Polish', NULL, '1 hour', 'POPULAR', 'Images/Car.jpg', 'Professional exterior car cleaning with polish for a shiny finish.', 'Exterior cleaning and polish.', '["Exterior wash and rinse","Exterior polish for shine","Tire cleaning","Windshield cleaning"]'::jsonb, '["Interior cleaning","Mechanical servicing","Scratch repair","Paint restoration"]'::jsonb, true, 4.7, '856'),
  ('Car Cleaning', 'Car Cleaning', 'Car Cleaning', 'Cleaning + Interior Polish', NULL, '1 hour', 'BESTSELLER', 'Images/Car.jpg', 'Professional interior car cleaning with polish for a fresh look.', 'Interior cleaning and polish.', '["Interior vacuuming","Seat cleaning","Carpet shampooing","Dashboard polish","Air freshener"]'::jsonb, '["Exterior cleaning","Mechanical servicing","Scratch repair","Upholstery repair"]'::jsonb, true, 4.7, '856'),
  ('Car Cleaning', 'Car Cleaning', 'Car Cleaning', 'Cleaning + Full', NULL, '2 hours', 'BESTSELLER', 'Images/Car.jpg', 'Comprehensive interior and exterior car cleaning with complete polish finish.', 'Complete interior and exterior cleaning with polish.', '["Exterior wash and rinse","Exterior polish for shine","Interior vacuuming","Seat cleaning","Carpet shampooing","Dashboard polish","Windshield cleaning","Tire cleaning and dressing","Air freshener"]'::jsonb, '["Mechanical servicing","Scratch repair","Paint restoration","Upholstery repair"]'::jsonb, true, 4.8, '856'),
  ('Water Tank Cleaning', 'Water Tank Cleaning', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', NULL, '2-4 hours', 'BESTSELLER', 'Images/WT.jpg', 'Deep cleaning and disinfection of overhead water tanks with professional equipment.', 'Water tank deep cleaning.', '["Tank inspection","Deep scrubbing","Disinfection","Debris removal","Water quality check"]'::jsonb, '["Structural repair","Plumbing replacement","Civil work"]'::jsonb, true, 4.8, '743'),
  ('Water Tank Cleaning', 'Water Tank Cleaning', 'Water Tank Cleaning', 'Commercial Water Tank Cleaning', NULL, 'Custom', 'CUSTOM', 'Images/WT.jpg', 'Custom commercial water tank cleaning. Share your requirements and our team will reach out for more information.', 'Commercial water tank cleaning planned after consultation.', '["Scope of cleaning will be decided after communication","Tank size, quantity and access requirements will be reviewed","Cleaning process and schedule will be confirmed with you","Custom quote will be shared before service"]'::jsonb, '["Fixed inclusions before consultation","Structural repair, plumbing replacement or civil work unless agreed separately","Any work not confirmed during communication"]'::jsonb, true, 4.8, '743');

-- Generated service_prices insert SQL from public/serviceCategory.js
INSERT INTO public.service_prices (location, category, tier, price) VALUES
  ('ghaziabad', 'Washroom Cleaning', 'Deep Washroom Cleaning', 249),
  ('ghaziabad', 'Washroom Cleaning', 'Basic Washroom Cleaning', 99),
  ('ghaziabad', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', 499),
  ('ghaziabad', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', 999),
  ('ghaziabad', 'Flat Cleaning', '1 BHK Flat Cleaning', 799),
  ('ghaziabad', 'Flat Cleaning', '2 BHK Flat Cleaning', 1299),
  ('ghaziabad', 'Flat Cleaning', '3 BHK Flat Cleaning', 1799),
  ('ghaziabad', 'Car Cleaning', 'Cleaning + Exterior Polish', 999),
  ('ghaziabad', 'Car Cleaning', 'Cleaning + Interior Polish', 799),
  ('ghaziabad', 'Car Cleaning', 'Cleaning + Full', 1699),
  ('ghaziabad', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', 599),
  ('ahmedabad', 'Washroom Cleaning', 'Deep Washroom Cleaning', 289),
  ('ahmedabad', 'Washroom Cleaning', 'Basic Washroom Cleaning', 189),
  ('ahmedabad', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', 499),
  ('ahmedabad', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', 1199),
  ('ahmedabad', 'Flat Cleaning', '1 BHK Flat Cleaning', 1499),
  ('ahmedabad', 'Flat Cleaning', '2 BHK Flat Cleaning', 2499),
  ('ahmedabad', 'Flat Cleaning', '3 BHK Flat Cleaning', 3499),
  ('ahmedabad', 'Car Cleaning', 'Cleaning + Exterior Polish', 999),
  ('ahmedabad', 'Car Cleaning', 'Cleaning + Interior Polish', 799),
  ('ahmedabad', 'Car Cleaning', 'Cleaning + Full', 1699),
  ('ahmedabad', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', 599),
  ('chennai', 'Washroom Cleaning', 'Deep Washroom Cleaning', 289),
  ('chennai', 'Washroom Cleaning', 'Basic Washroom Cleaning', 189),
  ('chennai', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', 499),
  ('chennai', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', 1199),
  ('chennai', 'Flat Cleaning', '1 BHK Flat Cleaning', 1499),
  ('chennai', 'Flat Cleaning', '2 BHK Flat Cleaning', 2499),
  ('chennai', 'Flat Cleaning', '3 BHK Flat Cleaning', 3499),
  ('chennai', 'Car Cleaning', 'Cleaning + Exterior Polish', 999),
  ('chennai', 'Car Cleaning', 'Cleaning + Interior Polish', 799),
  ('chennai', 'Car Cleaning', 'Cleaning + Full', 1699),
  ('chennai', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', 599),
  ('indore', 'Washroom Cleaning', 'Deep Washroom Cleaning', 289),
  ('indore', 'Washroom Cleaning', 'Basic Washroom Cleaning', 189),
  ('indore', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', 499),
  ('indore', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', 1199),
  ('indore', 'Flat Cleaning', '1 BHK Flat Cleaning', 1499),
  ('indore', 'Flat Cleaning', '2 BHK Flat Cleaning', 2499),
  ('indore', 'Flat Cleaning', '3 BHK Flat Cleaning', 3499),
  ('indore', 'Car Cleaning', 'Cleaning + Exterior Polish', 999),
  ('indore', 'Car Cleaning', 'Cleaning + Interior Polish', 799),
  ('indore', 'Car Cleaning', 'Cleaning + Full', 1699),
  ('indore', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', 599),
  ('betul', 'Washroom Cleaning', 'Deep Washroom Cleaning', 289),
  ('betul', 'Washroom Cleaning', 'Basic Washroom Cleaning', 189),
  ('betul', 'Kitchen Cleaning', 'Kitchen Deep Cleaning', 499),
  ('betul', 'Kitchen Cleaning', 'Modular Kitchen Deep Cleaning', 1199),
  ('betul', 'Flat Cleaning', '1 BHK Flat Cleaning', 1499),
  ('betul', 'Flat Cleaning', '2 BHK Flat Cleaning', 2499),
  ('betul', 'Flat Cleaning', '3 BHK Flat Cleaning', 3499),
  ('betul', 'Car Cleaning', 'Cleaning + Exterior Polish', 999),
  ('betul', 'Car Cleaning', 'Cleaning + Interior Polish', 799),
  ('betul', 'Car Cleaning', 'Cleaning + Full', 1699),
  ('betul', 'Water Tank Cleaning', 'Professional Water Tank Cleaning (500L-1000L)', 599);
